name: Test CLI homebrew install

on: push

jobs:
  test:
    runs-on: macos-latest
    steps:
      - uses: actions/checkout@v3
      - uses: maxim-lobanov/setup-xcode@v1
        with:
          xcode-version: latest-stable
      - run: |
          brew update
          brew cleanup
          brew update
          brew install Formula/xata.rb
          xata help
